- name: app-setup
  include_role:
    name: app-setup
  tasks_from: app-setup

- name: nodejs
  include_roles: 
    name: nodejs
  tasks_froom: nodejs

- name: systemd
  include_roles:
    name: systemd
  tasks_from: systemd